name: ${project.name}
version: ${project.version}
description: ${project.description}
author: Glynix
main: ${project.groupId}.Main

main: fr.dornacraft.minievents.Main
commands:
  event:
    permission: admin.event
    description: Gestion des événements.